In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
def load_csv(file_name):
    df=pd.read_csv(file_name,encoding='latin-1')
    return df

In [3]:
file_name="Data.csv"
df= load_csv(file_name)
Df_Restaurants=df.copy()

In [4]:
Df_Restaurants

,MinOrder,City,Name,Delviry_Min,Delviry_Max,Delivery_Money,Money,Sushi,Burger,Salad,...,Ice_cream,Brunch,Hummus,Crepe,Asian,Homemade,Meat_fish,Kids_meals,Kids,Rate
0,50,ashdod,Burger King | Ashdod,20,30,12,$$$,0,1,0,...,0,0,0,0,0,0,0,0,0,8.0
1,50,ashdod,Ruben | Ashdod,25,35,12,$$,0,1,0,...,0,0,0,0,0,0,0,0,0,8.2
2,50,ashdod,Schnitzel Factory,30,40,16,$$,0,0,0,...,0,0,0,0,0,0,0,0,0,8.6
3,50,ashdod,Pita Basta | Ashdod,20,30,12,$$,0,0,0,...,0,0,0,0,0,0,0,0,0,8.4
4,50,ashdod,Del Pesto | Sea Mall,30,40,16,$$,0,0,0,...,0,0,0,0,0,0,0,0,0,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,50,yavne,B Burger | Yavne,0,0,12,$$,0,1,0,...,0,0,0,0,0,0,0,0,0,8.6
2023,50,yavne,Ami's Hummus,0,0,14,$$$,0,0,1,...,0,0,1,0,0,0,0,0,0,9.2
2024,50,yavne,Haderech Lalehem | Yavne,0,0,10,$$,0,0,1,...,0,0,0,0,0,0,0,0,0,8.8
2025,50,yavne,CafÃ© Greg | Yavne,0,0,14,$$,0,0,0,...,0,0,0,0,0,0,0,0,0,8.2
2026,50,yavne,Marlen Hummus,0,0,14,$$,0,0,0,...,0,0,1,0,0,0,0,0,0,8.8

In [5]:
Df_Restaurants.info()##check if there is null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2027 entries, 0 to 2026
Data columns (total 47 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   MinOrder        2027 non-null   int64
 1   City            2027 non-null   object
 2   Name            2027 non-null   object
 3   Delviry_Min     2027 non-null   int64
 4   Delviry_Max     2027 non-null   int64
 5   Delivery_Money  2027 non-null   int64
 6   Money           2027 non-null   object
 7   Sushi           2027 non-null   int64
 8   Burger          2027 non-null   int64
 9   Salad           2027 non-null   int64
 10  Kebab           2027 non-null   int64
 11  Pizza           2027 non-null   int64
 12  Fish            2027 non-null   int64
 13  Sandwitch       2027 non-null   int64
 14  Steak           2027 non-null   int64
 15  Cafe            2027 non-null   int64
 16  Street_Food     2027 non-null   int64
 17  Healthy         2027 non-null   int64
 18  Pasta           2027 non-null   int64
 19  Dessert         2027 non-null   int64
 20  Vegetarian      2027 non-null   int64
 21  Noodles         2027 non-null   int64
 22  American        2027 non-null   int64
 23  Mediterranean   2027 non-null   int64
 24  italian         2027 non-null   int64
 25  Japanese        2027 non-null   int64
 26  Smoothie        2027 non-null   int64
 27  Breakfast       2027 non-null   int64
 28  Vegan           2027 non-null   int64
 29  Georgian        2027 non-null   int64
 30  Kosher          2027 non-null   int64
 31  Pharmacy        2027 non-null   int64
 32  Grocery         2027 non-null   int64
 33  Greek           2027 non-null   int64
 34  Bakery          2027 non-null   int64
 35  BBQ             2027 non-null   int64
 36  Alcohol         2027 non-null   int64
 37  Ice_cream       2027 non-null   int64
 38  Brunch          2027 non-null   int64
 39  Hummus          2027 non-null   int64
 40  Crepe           2027 non-null   int64
 41  Asian           2027 non-null   int64
 42  Homemade        2027 non-null   int64
 43  Meat_fish       2027 non-null   int64
 44  Kids_meals      2027 non-null   int64
 45  Kids            2027 non-null   int64
 46  Rate            2027 non-null   float64
dtypes: float64(1), int64(43), object(3)
memory usage: 744.4+ KB

In [6]:
Df_Restaurants=df.drop_duplicates(subset=["Name"],keep='first')

In [7]:
Df_Rows_Num=Df_Restaurants.index

In [8]:
print(Df_Rows_Num)

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026],
           dtype='int64', length=2027)

In [9]:
for i in Df_Rows_Num:##שינוי עמודת הכסף לאורך הסטרינג כאשר כמות דולרים היא המספור
    Df_Restaurants["Money"][i]=(len(Df_Restaurants["Money"][i]))

C:\Users\3169~1\AppData\Local\Temp/ipykernel_6936/2470191991.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Df_Restaurants["Money"][i]=(len(Df_Restaurants["Money"][i]))

In [10]:
Df_Restaurants

,MinOrder,City,Name,Delviry_Min,Delviry_Max,Delivery_Money,Money,Sushi,Burger,Salad,...,Ice_cream,Brunch,Hummus,Crepe,Asian,Homemade,Meat_fish,Kids_meals,Kids,Rate
0,50,ashdod,Burger King | Ashdod,20,30,12,3,0,1,0,...,0,0,0,0,0,0,0,0,0,8.0
1,50,ashdod,Ruben | Ashdod,25,35,12,2,0,1,0,...,0,0,0,0,0,0,0,0,0,8.2
2,50,ashdod,Schnitzel Factory,30,40,16,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.6
3,50,ashdod,Pita Basta | Ashdod,20,30,12,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.4
4,50,ashdod,Del Pesto | Sea Mall,30,40,16,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,50,yavne,B Burger | Yavne,0,0,12,2,0,1,0,...,0,0,0,0,0,0,0,0,0,8.6
2023,50,yavne,Ami's Hummus,0,0,14,3,0,0,1,...,0,0,1,0,0,0,0,0,0,9.2
2024,50,yavne,Haderech Lalehem | Yavne,0,0,10,2,0,0,1,...,0,0,0,0,0,0,0,0,0,8.8
2025,50,yavne,CafÃ© Greg | Yavne,0,0,14,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.2
2026,50,yavne,Marlen Hummus,0,0,14,2,0,0,0,...,0,0,1,0,0,0,0,0,0,8.8

In [11]:
dict_cities={"ashdod":0,"beer-sheva":1,"hasharon":2,"herzliya":3,"jerusalem":4,"ness-ziona---rehovot":5,"netanya":6,"pardes-hanna":7,"petah-tikva":8,"rishon-lezion":9,"tel-aviv":10,"yavne":11}

In [12]:
for key,value in dict_cities.items():
    Df_Restaurants["City"].replace({key:value}, inplace=True)

In [13]:
Df_Restaurants["Delviry_Min"].replace({0:np.nan}, inplace=True)
Df_Restaurants["Delviry_Max"].replace({0:np.nan}, inplace=True)

In [14]:
#df_res[col1].fillna(df_res[col1].median(),inplace=True)
for key,value in dict_cities.items():
    df_help=Df_Restaurants.loc[Df_Restaurants["City"]==value]
    median_min=df_help["Delviry_Min"].median()
    median_max=df_help["Delviry_Max"].median()
    print(median_min,median_max)
    Df_Restaurants.loc[(Df_Restaurants['City']==value)&(Df_Restaurants['Delviry_Min'].isnull()),'Delviry_Min']=median_min
    Df_Restaurants.loc[(Df_Restaurants['City']==value)&(Df_Restaurants['Delviry_Max'].isnull()),'Delviry_Max']=median_max

30.0 40.0
35.0 45.0
35.0 45.0
25.0 35.0
35.0 45.0
25.0 35.0
42.5 52.5
25.0 35.0
35.0 45.0
35.0 45.0
30.0 40.0
20.0 30.0

In [15]:
Df_Restaurants

,MinOrder,City,Name,Delviry_Min,Delviry_Max,Delivery_Money,Money,Sushi,Burger,Salad,...,Ice_cream,Brunch,Hummus,Crepe,Asian,Homemade,Meat_fish,Kids_meals,Kids,Rate
0,50,0,Burger King | Ashdod,20.0,30.0,12,3,0,1,0,...,0,0,0,0,0,0,0,0,0,8.0
1,50,0,Ruben | Ashdod,25.0,35.0,12,2,0,1,0,...,0,0,0,0,0,0,0,0,0,8.2
2,50,0,Schnitzel Factory,30.0,40.0,16,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.6
3,50,0,Pita Basta | Ashdod,20.0,30.0,12,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.4
4,50,0,Del Pesto | Sea Mall,30.0,40.0,16,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022,50,11,B Burger | Yavne,20.0,30.0,12,2,0,1,0,...,0,0,0,0,0,0,0,0,0,8.6
2023,50,11,Ami's Hummus,20.0,30.0,14,3,0,0,1,...,0,0,1,0,0,0,0,0,0,9.2
2024,50,11,Haderech Lalehem | Yavne,20.0,30.0,10,2,0,0,1,...,0,0,0,0,0,0,0,0,0,8.8
2025,50,11,CafÃ© Greg | Yavne,20.0,30.0,14,2,0,0,0,...,0,0,0,0,0,0,0,0,0,8.2
2026,50,11,Marlen Hummus,20.0,30.0,14,2,0,0,0,...,0,0,1,0,0,0,0,0,0,8.8

In [16]:
Df_Restaurants.to_csv("Corrected_Data.csv")